# Generated by Django 5.0.6 on 2024-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('email',models.EmailField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
