# Generated by Django 4.2.14 on 2024-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(default='000', upload_to='coach/'),
        ),
    ]
