# Generated by Django 5.0.3 on 2024-08-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0004_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player',
            new_name='player1',
        ),
    ]
