# Generated by Django 4.2.14 on 2024-08-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0005_rename_player_player1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=200)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bapp.coach')),
            ],
        ),
    ]
