# Generated by Django 4.2.14 on 2024-08-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0006_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='lastname',
        ),
        migrations.AddField(
            model_name='coach',
            name='coachname',
            field=models.CharField(default='ydghuyg', max_length=200),
        ),
    ]
