# Generated by Django 5.0.3 on 2024-08-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0007_remove_coach_firstname_remove_coach_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='c_id',
            new_name='co_id',
        ),
    ]
