# Generated by Django 5.0.3 on 2024-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0008_rename_c_id_team_co_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='co_id',
        ),
        migrations.AddField(
            model_name='team',
            name='co_name',
            field=models.CharField(default='jksfhk', max_length=200),
        ),
    ]
