# Generated by Django 5.0.3 on 2024-08-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0009_remove_team_co_id_team_co_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='co_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bapp.coach'),
        ),
    ]
