# Generated by Django 5.0.3 on 2024-08-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0010_alter_team_co_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='co_name',
            new_name='co_id',
        ),
    ]
