# Generated by Django 5.0.3 on 2024-08-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0011_rename_co_name_team_co_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='co_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bapp.coach'),
        ),
    ]
