# Generated by Django 5.0.3 on 2024-08-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0012_alter_team_co_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='co_id',
            new_name='coach_name',
        ),
    ]
