# Generated by Django 5.0.3 on 2024-08-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0013_rename_co_id_team_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_tb',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bapp.coach')),
                ('ply_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bapp.player1')),
                ('tea_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bapp.team')),
            ],
        ),
    ]
